version: "3"
services:
  php:
    container_name: php_${PROJECT_NAME}
    build:
      context: ./
      dockerfile: docker/configs/php/Dockerfile
      args:
        WORKDIR: ${WORKDIR}
    environment:
      WORKDIR: ${WORKDIR}
      XDEBUG_CONFIG: remote_host=127.0.0.1
      PHP_IDE_CONFIG: serverName=docker
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./:${WORKDIR}
      - ./logs/nginx:/var/log/nginx

  db:
    image: mysql/mysql-server:8.0.23
    container_name: db
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - db-hillel:/var/lib/mysql
    ports:
      - "33060:3306"

volumes:
  db-hillel:
