version: "3"
services:
  php:
    container_name: php_${PROJECT_NAME}
    build:
      context: ./
      dockerfile: docker/configs/php/Dockerfile
      args:
        WORKDIR: ${WORKDIR}
    environment:
      WORKDIR: ${WORKDIR}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      XDEBUG_CONFIG: remote_host=127.0.0.1
      PHP_IDE_CONFIG: serverName=docker
    volumes:
      - ./:${WORKDIR}
      - ./logs/nginx:/var/log/nginx
    links:
      - db

  db:
    image: mysql:latest
    container_name: db_${PROJECT_NAME}
    environment:
      WORKDIR: ${WORKDIR}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-hillel:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_PORT}:3306

  nginx:
    image: nginx:latest
    container_name: nginx_${PROJECT_NAME}
    volumes:
      - ./:${WORKDIR}
      - ./docker/configs/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    links:
      - php

volumes:
  db-hillel:
