version: "3"
services:
  php:
    container_name: php_${PROJECT_NAME}
    build:
      context: ./
      dockerfile: docker/configs/php/Dockerfile
      args:
        WORKDIR: ${WORKDIR}
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    environment:
      WORKDIR: ${WORKDIR}
      XDEBUG_CONFIG: remote_host=127.0.0.1
      PHP_IDE_CONFIG: serverName=docker
    volumes:
      - ./:${WORKDIR}
      - ./logs/nginx:/var/log/nginx

  db:
    image: mysql/mysql-server:8.0.23
    container_name: db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: hillel
      MYSQL_USER: hillel
      MYSQL_PASSWORD: hillel!23
      MYSQL_ROOT_PASSWORD: hillel!23
    volumes:
      - db-hillel:/var/lib/mysql
    ports:
      - "33060:3306"

volumes:
  db-hillel:
